using MolBhav.Domain.Common.Abstractions;
using MolBhav.Domain.Common.Primitives;
using MolBhav.Domain.SharedKernel;

namespace MolBhav.Domain.Identity;

/// <summary>
/// A one-time verification code issued for a mobile-number login attempt (BRD §7). The plaintext code is never
/// stored — only a salted hash — so it is generated by the caller and handed in already hashed
/// (see <c>IOtpCodeGenerator</c> in Application/Infrastructure).
/// </summary>
public sealed class OtpChallenge : AggregateRoot<Guid>, IAuditableEntity
{
    public const int MaxAttempts = 5;

    /// <summary>How long a code stays valid after issue.</summary>
    public static readonly TimeSpan Lifetime = TimeSpan.FromMinutes(5);

    /// <summary>Minimum gap between two codes issued to the same phone number (abuse/cost control).</summary>
    public static readonly TimeSpan ResendCooldown = TimeSpan.FromSeconds(60);

    private OtpChallenge(Guid id, PhoneNumber phoneNumber, string codeHash, DateTimeOffset issuedAtUtc)
        : base(id)
    {
        PhoneNumber = phoneNumber;
        CodeHash = codeHash;
        ExpiresAtUtc = issuedAtUtc.Add(Lifetime);
        AttemptCount = 0;
    }

    /// <summary>Required by EF Core for materialisation.</summary>
    private OtpChallenge()
    {
        PhoneNumber = null!;
        CodeHash = string.Empty;
    }

    public PhoneNumber PhoneNumber { get; private set; }

    public string CodeHash { get; private set; }

    public DateTimeOffset ExpiresAtUtc { get; private set; }

    public DateTimeOffset? ConsumedAtUtc { get; private set; }

    public int AttemptCount { get; private set; }

    public DateTimeOffset CreatedAtUtc { get; private set; }

    public Guid? CreatedBy { get; private set; }

    public DateTimeOffset? UpdatedAtUtc { get; private set; }

    public Guid? UpdatedBy { get; private set; }

    public static OtpChallenge Issue(PhoneNumber phoneNumber, string codeHash, DateTimeOffset nowUtc)
    {
        ArgumentNullException.ThrowIfNull(phoneNumber);
        ArgumentException.ThrowIfNullOrWhiteSpace(codeHash);

        return new OtpChallenge(Guid.CreateVersion7(), phoneNumber, codeHash, nowUtc);
    }

    /// <summary>True while the code can still be presented (not consumed, not expired, attempts remain).</summary>
    public bool IsActive(DateTimeOffset nowUtc) =>
        ConsumedAtUtc is null && nowUtc < ExpiresAtUtc && AttemptCount < MaxAttempts;

    /// <summary>
    /// Checks <paramref name="presentedCodeHash"/> against the stored hash. A wrong/expired/exhausted attempt still
    /// records itself (attempt count) so brute-force protection works — callers must persist the result regardless
    /// of the business outcome (see <c>VerifyOtpCommandHandler</c> for why this is still a committed <c>Result.Success</c>
    /// at the application layer: EF only ever emits an UPDATE for properties that actually changed, so committing
    /// after a terminal, no-op check below is harmless).
    /// </summary>
    public OtpVerificationOutcome Verify(string presentedCodeHash, DateTimeOffset nowUtc)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(presentedCodeHash);

        if (ConsumedAtUtc is not null)
        {
            return OtpVerificationOutcome.AlreadyUsed;
        }

        if (nowUtc >= ExpiresAtUtc)
        {
            return OtpVerificationOutcome.Expired;
        }

        if (AttemptCount >= MaxAttempts)
        {
            return OtpVerificationOutcome.TooManyAttempts;
        }

        AttemptCount++;

        if (!string.Equals(CodeHash, presentedCodeHash, StringComparison.Ordinal))
        {
            return AttemptCount >= MaxAttempts ? OtpVerificationOutcome.TooManyAttempts : OtpVerificationOutcome.IncorrectCode;
        }

        ConsumedAtUtc = nowUtc;
        return OtpVerificationOutcome.Verified;
    }
}
